ECommerceApp.Web/Componets/CategoryMenuViewComponent.cs
using ECommerceApp.Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
namespace StoreApp.Components
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoryMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _manager.CategoryService.GetAllCategoryAsync();
            return View(categories.Data);
        }
    }
}

ECommerceApp.Web/Controllers/ProductController.cs
using System.Linq.Expressions;
using ECommerceApp.Application.DTOs;
using ECommerceApp.Application.Interfaces;
using ECommerceApp.Core.Models;
using ECommerceApp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceApp.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<ApplicationUser> _userManager;
        public ProductController(IServiceManager manager, UserManager<ApplicationUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }
        [HttpGet("Index")]
        [HttpGet("Product/{categoryName?}")]
        public async Task<IActionResult> Index(string? categoryName = null, decimal? minPrice = null, decimal? maxPrice = null, bool sorted = false)
        {
            ViewBag.CurrentPage = "Index";
            ViewBag.PageTitle = "Products";
            IEnumerable<Product> products;

            Expression<Func<Product, bool>> filter = p =>
                (!minPrice.HasValue || p.Price >= minPrice.Value) &&
                (!maxPrice.HasValue || p.Price <= maxPrice.Value) &&
                (string.IsNullOrEmpty(categoryName) || p.Category.Name == categoryName);

            Expression<Func<Product, object>>[] includes = new Expression<Func<Product, object>>[]{
                    p => p.Category,
                    p => p.Seller,
                    p => p.Reviews};

            var result = await _manager.ProductService.GetAllProductInculudeAndFilteredAsync(filter, includes);
            products = result.Data ?? new List<Product>();

            var viewModel = new ProductListViewModel
            {
                Products = products,
                Filter = new FilterViewModel
                {
                    MinPrice = minPrice,
                    MaxPrice = maxPrice,
                    SortOrder = sorted ? "Sorted" : "Unsorted",
                    CategoryName = categoryName
                }
            };

            return View(viewModel);
        }
        [HttpGet("Product/Details/{productId?}")]
        public async Task<IActionResult> Details(int productId)
        {
                
            var result = await _manager.ProductService.GetAllInculedeThenInculudeveAsync(productId);
            var user = await _userManager.GetUserAsync(User);
            var product = result.Data!.FirstOrDefault();
            if (result.Success)
            {
                var model = new ProductByReviewDetailViewModel
                {
                    Product = product!,
                    ReviewInsertDTO = new ReviewInsertDTO
                    {
                        ProductId = product!.ProductId,
                        CustomerId = user?.Id ?? string.Empty
                    }
                };
                return View(model);
            }
            else
            {
                return NotFound();
            }

        }
        [Authorize]
        [HttpGet("Product/AddProduct")]
        public async Task<IActionResult> AddProduct()
        {
            var categories = await _manager.CategoryService.GetAllCategoryAsync();
            var viewModel = new ProductInsertViewModel
            {
                Categories = categories.Data!
            };
            return View(viewModel);
        }
        [Authorize]
        [HttpPost("Product/AddProduct")]
        public async Task<IActionResult> AddProduct(ProductInsertViewModel viewModel, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory()
                , "wwwroot", "images", file.FileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                var product = viewModel.Product;

                var user = await _userManager.GetUserAsync(User);

                product.ImageUrl = String.Concat("/images/", file.FileName);
                product.SellerId = user!.Id;

                var result = await _manager.ProductService.AddProductAsync(product);
                if (result.Success)
                {
                    return RedirectToAction("Index", "Product");
                }

            }
            var categories = await _manager.CategoryService.GetAllCategoryAsync();
            viewModel.Categories = categories.Data ?? new List<Category>();

            return View(viewModel);
        }

    }
    

}
/*
public async Task<IActionResult> Index(decimal? minPrice, decimal? maxPrice, string sortOrder = "asc", bool Sorted = false)
{
    ViewBag.CurrentPage = "Index";
    ViewBag.PageTitle = "Products";
    IEnumerable<Product> products;
    if (Sorted)
    {
        Expression<Func<Product, bool>> filter = p =>
            (!minPrice.HasValue || p.Price >= minPrice.Value) &&
            (!maxPrice.HasValue || p.Price <= maxPrice.Value);

        var result = await _manager.ProductService.GetFilteredProductsAsync(filter, sortOrder);
        products = result.Data ?? new List<Product>();
    }
    else
    {
        var result = await _manager.ProductService.GetAllProductsAsync();
        products = result.Data ?? new List<Product>();
    }

    var viewModel = new ProductListViewModel
    {
        Products = products,
        Filter = new FilterViewModel
        {
            MinPrice = minPrice,
            MaxPrice = maxPrice,
            SortOrder = sortOrder
        }
    };

    return View(viewModel);
}
*/
/*
[HttpGet("Product/{categoryName}")]
public async Task<IActionResult> ProductsByCategory(string categoryName, decimal? minPrice, decimal? maxPrice, string sortOrder = "asc", bool Sorted = false)
{
    ViewBag.PageTitle = $"Products in {categoryName} - {(Sorted ? "Sorted" : "Unsorted")}";
    ViewBag.CurrentPage = "ProductsByCategory";
    ViewBag.CategoryName = categoryName;
    IEnumerable<Product> products;
    if (Sorted)
    {
        Expression<Func<Product, bool>> filter = p =>
            (!minPrice.HasValue || p.Price >= minPrice.Value) &&
            (!maxPrice.HasValue || p.Price <= maxPrice.Value) &&
            (p.Category.Name == categoryName);

        var result = await _manager.ProductService.GetFilteredProductsAsync(filter, sortOrder);
        products = result.Data ?? new List<Product>();
    }
    else
    {
        var result = await _manager.ProductService.GetProductsByCategoryAsync(categoryName);
        products = result.Data ?? new List<Product>();
    }
    var viewModel = new ProductListViewModel
    {
        Products = products,
        Filter = new FilterViewModel
        {
            MinPrice = minPrice,
            MaxPrice = maxPrice,
            SortOrder = sortOrder
        }
    };
    return View(viewModel);
}
*/

ECommerceApp.Web/Views/Product/AddProduct.cshtml
@model ProductInsertViewModel

@{
    ViewBag.Title = "Add Product";
}

<h2>Add Product</h2>

<form asp-action="AddProduct" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="@Model.Product.Name"></label>
        <input asp-for="@Model.Product.Name" class="form-control" />
        <span asp-validation-for="@Model.Product.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Product.Description"></label>
        <textarea asp-for="@Model.Product.Description" class="form-control"></textarea>
        <span asp-validation-for="@Model.Product.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Product.Price"></label>
        <input asp-for="@Model.Product.Price" class="form-control" type="number" />
        <span asp-validation-for="@Model.Product.Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="@Model.Product.CategoryId"></label>
        <select asp-for="@Model.Product.CategoryId" class="form-control">
            <option value="">Select Category</option>
            @foreach (var category in Model.Categories)
            {
                <option value="@category.CategoryId">@category.Name</option>
            }
        </select>
        <span asp-validation-for="@Model.Product.CategoryId" class="text-danger"></span>
    </div>
    <div class="form-group my-3">
        <img id="imagePreview" src="#" alt="Image Preview" style="display:none; max-height: 300px;" />
    </div>
     <div class="form-group my-3">
        <label asp-for="@Model.Product.ImageUrl"></label>
        <input asp-for="@Model.Product.ImageUrl" id="imageUpload" name="file" type="file" class="form-control" placeholder="ImageUrl" onchange="previewImage(event)" />
        <span asp-validation-for="@Model.Product.ImageUrl" class="text-danger"></span>
    </div>

    <div class="form-group text-end my-3">
        <button type="submit" class="btn btn-primary">Add Product</button>
    </div>
</form>

@section Scripts {
    <script src="~/js/imagePreview.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

ECommerceApp.Web/Views/Product/Details.cshtml
@model ProductByReviewDetailViewModel

@{
    ViewBag.Title = Model.Product.Name;
}

<link rel="stylesheet" href="~/css/ProductDetail.css" />
<div class="product-detail-container">
    <div class="product-detail">
        <img src="@Model.Product.ImageUrl" alt="@Model.Product.Name" class="product-image">
        <div class="product-info">
            <div class="seller-info">
                <img src="@Model.Product.Seller.ProfilePictureUrl" class="profile-picture rounded-circle"
                    alt="@Model.Product.Seller.FullName's Profile Picture">
                <p><strong>Seller: </strong>@Model.Product.Seller.FullName</p>
            </div>
            <h2>@Model.Product.Name</h2>
            <p>@Model.Product.Description</p>
            <p><strong>Price: </strong>@Model.Product.Price.ToString("C")</p>
            <p><strong>Category: </strong>@Model.Product.Category.Name</p>
            <div class="product-actions">
                <a href="javascript:history.back()" class="btn back-btn">Back</a>
                <a class="btn buy-btn">Buy Now</a>   <!-- Not yet implamented  --> 
                <a class="btn btn-success btn-half-size" onclick="addToCart(@Model.Product.ProductId)">Add to Cart</a>
            </div>
        </div>
    </div>
</div>

<div class="reviews-section">
    <h3>Customer Reviews</h3>

    @if (Model.Product?.Reviews != null && Model.Product.Reviews.Any())
    {
        @foreach (var review in Model.Product.Reviews)
        {
            <div class="card review-card mb-3">
                <div class="card-body position-relative">
                    <div class="d-flex align-items-center mb-2">
                        <img src="@review.Customer.ProfilePictureUrl" alt="Customer Image" class="rounded-circle" width="30" height="30">
                        <h5 class="card-title ml-2 mb-0">@review.Customer.FullName</h5>
                    </div>
                    <div class="context-end">
                        @for (int i = 1; i <= 5; i++)
                        {
                            if (i <= review.Rating)
                            {
                                <span class="star">&#9733;</span> 
                            }
                            else
                            {
                                <span class="star">&#9734;</span> 
                            }
                        }
                    </div>
                    <p class="card-text">@review.Content</p>
                </div>
            </div>
        }
    }
    else
    {
        <p>Be the first to write a review.</p>
    }
    <div id="new-review">
    </div>
</div>
<div>
    @await Html.PartialAsync("_ReviewFormPartial", Model.ReviewInsertDTO)
</div>
<script src="~/js/additemtocart.js"></script>

ECommerceApp.Web/Views/Product/Index.cshtml
@model ProductListViewModel
@{
    ViewBag.Title = ViewBag.PageTitle;
}

<div class="container my-5">
    <div class="row mt-4">
        <div class="col-md-2 mt-4 sticky-sidebar">
            @await Component.InvokeAsync("CategoryMenu")
            <partial name="_FilterAndSort" model="@Model.Filter" />
        </div>

        <div class="col-md-10">
            <div class="row mt-4">
                @foreach (var product in Model.Products)
                {
                    <div class="col-md-4 mb-4">
                        <partial name="_ProductCard" model="@product" />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ECommerceApp.Web/Views/Product/ProductsByCategory.cshtml
@model ProductListViewModel
@{
    ViewBag.Title = ViewBag.PageTitle;
}
<div class="container my-5">
    <div class="row mt-4">
        <div class="col-md-2 mt-4">
            @await Component.InvokeAsync("CategoryMenu")
            <partial name="_FilterAndSort" model="@Model.Filter" />
        </div>
        
        <div class="col-md-10">
            <div class="row mt-4">
                @foreach(var product in Model.Products)
                {
                    <div class="col-md-4 mb-4">
                        <partial name="_ProductCard" model=@product />
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ECommerceApp.Web/Views/Product/_FilterAndSort.cshtml
@model FilterViewModel

<h3 class="text-center mt-4">Filter and Sort Products</h3>

@if (ViewBag.CurrentPage == "Index")
{
    <form asp-action="@ViewBag.CurrentPage" method="get">
        <div class="form-group">
            <label for="minPrice">Min Price:</label>
            <input type="number" class="form-control" step="0.01" id="minPrice" name="minPrice" value="@Model.MinPrice" />
        </div>
        <div class="form-group mt-2">
            <label for="maxPrice">Max Price:</label>
            <input type="number" class="form-control" step="0.01" id="maxPrice" name="maxPrice" value="@Model.MaxPrice" />
        </div>
        <input type="hidden" name="Sorted" value="true" />
        <button type="submit" class="btn btn-primary mt-3">Filter</button>
    </form>
}
else if (ViewBag.CurrentPage == "ProductsByCategory")
{
    <form asp-action="@ViewBag.CurrentPage" method="get">
        <input type="hidden" name="categoryName" value="@ViewBag.CategoryName" />
        <div class="form-group">
            <label for="minPriceCategory">Min Price:</label>
            <input type="number" class="form-control" step="0.01" id="minPriceCategory" name="minPrice" value="@Model.MinPrice" />
        </div>
        <div class="form-group mt-2">
            <label for="maxPriceCategory">Max Price:</label>
            <input type="number" class="form-control" step="0.01" id="maxPriceCategory" name="maxPrice" value="@Model.MaxPrice" />
        </div>
        <input type="hidden" name="Sorted" value="true" />
        <button type="submit" class="btn btn-primary mt-3">Filter by Category</button>
    </form>
}

ECommerceApp.Web/Views/Product/_ProductCard.cshtml
@model Product

@{
    var averageRating = Model.Reviews.Any() ? Model.Reviews.Average(r => r.Rating) : 0;
    var filledStars = (int)Math.Floor(averageRating);
    var halfStar = (averageRating - filledStars) >= 0.5;

}

<link rel="stylesheet" href="~/css/ProductCard.css" />

<div class="card">
    <img src="@Model.ImageUrl" class="card-img-top" alt="@Model.Name">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <a asp-controller="Seller" asp-action="Profile" asp-route-sellerId="@Model.Seller.Id"
                class="d-flex align-items-center text-decoration-none">
                <img src="@Model.Seller.ProfilePictureUrl" class="profile-picture rounded-circle"
                    alt="@Model.Seller.FullName's Profile Picture">
                <span class="ml-2">@Model.Seller.FullName</span>
            </a>
            <div class="d-flex">
                <a asp-controller="Product" asp-action="Details" asp-route-productId="@Model.ProductId"
                    class="btn btn-primary btn-half-size mr-2">
                    <i class="fas fa-info-circle"></i>
                </a>
                <button class="btn btn-success btn-half-size" onclick="addToCart(@Model.ProductId)">
                    <i class="fas fa-shopping-cart"></i>
                </button>
            </div>
        </div>
        <h5 class="card-title">@Model.Name</h5>
            <div class="context-end">
         @for (int i = 1; i <= 5; i++)
        {
            if (i <= filledStars)
            {
                <span class="star">&#9733;</span> 
            }
            else if (i == filledStars + 1 && halfStar)
            {
                <span class="star">&#9734;</span> 
            }
            else
            {
                <span class="star">&#9734;</span> 
            }
        }
    </div>
        <p class="card-text">@Model.Description</p>
        <p class="card-text">
            <strong>@Model.Price.ToString("C")</strong>
        </p>
    </div>
</div>

<script src="~/js/additemtocart.js"></script>