ECommerceApp.Web/Componets/CartItemCountViewComponent.cs
using ECommerceApp.Application.Interfaces;
using ECommerceApp.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
namespace StoreApp.Components
{
    public class CartItemCountViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<ApplicationUser> _userManager;

        public CartItemCountViewComponent(IServiceManager manager, UserManager<ApplicationUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var user = await _userManager.GetUserAsync(UserClaimsPrincipal);
            int count = await _manager.ShoppingCartService.GetCartItemsCountAsync(user!.Id);
            return Content(count.ToString());
        }
    }
}

ECommerceApp.Web/Componets/UserViewComponent.cs
using ECommerceApp.Core.Models;
using ECommerceApp.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

public class UserViewComponent : ViewComponent
{
    private readonly UserManager<ApplicationUser> _userManager;

    public UserViewComponent(UserManager<ApplicationUser> userManager)
    {
        _userManager = userManager;
    }
    [Authorize]
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var user = await _userManager.GetUserAsync(UserClaimsPrincipal);
        var userInfo = new UserInfo
        {
                FullName = user!.FullName,
                ProfilePictureUrl = user.ProfilePictureUrl!
        };
            return View("Default", userInfo);
        }
}

ECommerceApp.Web/Controllers/OrderController.cs
using ECommerceApp.Application.Interfaces;
using ECommerceApp.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceApp.Web.Controllers
{       
    [Authorize]
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<ApplicationUser> _userManager;
        public OrderController(IServiceManager manager, UserManager<ApplicationUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return RedirectToAction("MyOrdes");
        }
        [HttpGet]
        public async Task<IActionResult> MyOrders()
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _manager.OrderService.GetPurchasesByUserIdAsync(user!.Id);
            return View(result.Data);
        }
        [HttpGet]
        public async Task<IActionResult> PurchasedItems()
        {
            var user = await _userManager.GetUserAsync(User);
            var result = await _manager.OrderService.GetSalesByUserIdAsync(user!.Id);
            return View(result.Data);
        }
    }
}

ECommerceApp.Web/Controllers/ShoppingCartController.cs
using ECommerceApp.Application.Interfaces;
using ECommerceApp.Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceApp.Web.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(IServiceManager manager, UserManager<ApplicationUser> userManager)
        {
            _manager = manager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var cartItems =await _manager.ShoppingCartService.GetCartItemsAsync(user!.Id);
            return View(cartItems.Data);
        }
    }
}

ECommerceApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - ECommerceApp</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/Navbar.css" />    
    <link rel="stylesheet" href="~/css/review.css" />
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.6.0-web/css/all.min.css" />
    <link rel="icon" type="image/jpg" href="~/images/favicon.jpg" />
</head>
<body>
    <header>
        <partial name="_Navbar" />
    </header>
    <div class="container my-5">
        @RenderBody()
    </div>
    <footer></footer>
    @RenderSection("Scripts", required: false)
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ECommerceApp.Web/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">ECommerceApp</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                </li>
                @if(User.Identity != null && User.Identity.IsAuthenticated)
                {
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="AddProduct">Add Product</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Order" asp-action="MyOrders">My Orders</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Order" asp-action="PurchasedItems">Purchased Items</a>
                </li>
                }
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 visible-on-small-screen">
                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <li class="nav-item d-flex align-items-center">
                        @await Component.InvokeAsync("User")
                    </li>
                    <li class="nav-item">
                    <li class="nav-item d-flex align-items-center">
                            @await Component.InvokeAsync("CartItemCount")
                    </li>
                    <a class="nav-link" asp-controller="ShoppingCart" asp-action="Index">
                        <i class="fas fa-shopping-cart"></i>
                        <span class="badge badge-pill badge-danger"></span>
                    </a>
                    </li>
                    <li class="nav-item">
                        <form asp-controller="Account" asp-action="Logout" method="post">
                            <button type="submit" class="btn btn-link">
                                <i class="fas fa-sign-out-alt"></i>
                            </button>
                        </form>
                    </li>

                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
                    </li>
                }
            </ul>

        </div>
    </div>
</nav>

ECommerceApp.Web/Views/Shared/_ReviewFormPartial.cshtml
@model ReviewInsertDTO
<div class="card my-3">
    <div class="card-header">
        Write a Review
    </div>

    <div class="card-body">
        <div id="reviewFormResult" class="mt-3"></div>
        <form id="reviewForm" method="post">
            <input type="hidden" asp-for="ProductId" />
            <input type="hidden" asp-for="CustomerId" />
            <div class="form-group">
                <label asp-for="Content">Your Review:</label>
                <textarea asp-for="Content" class="form-control my-3"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating">Rating:</label>
                <div class="star-rating">
                    <span class="star" data-value="1">&#9734;</span>
                    <span class="star" data-value="2">&#9734;</span>
                    <span class="star" data-value="3">&#9734;</span>
                    <span class="star" data-value="4">&#9734;</span>
                    <span class="star" data-value="5">&#9734;</span>
                </div>
                <input type="hidden" asp-for="Rating" id="Rating" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <button type="button" onclick="submitReviewForm()" class="btn btn-primary mt-3">Submit Review</button>
        </form>
    </div>
</div>

<script src="~/js/addreview.js"></script>
<script src="~/js/starrating.js"></script>